### ISSUE TITLE
Problems French subtitles accent like "???"Solution pour les sous-titres??

### ISSUE THREAD

**Issue by mistertest** [yify-pop/yify-pop#106]
Hello,

My final probem is the french subtitles with special characters.
So subtitles are not in UTF8, is there a solution for this or not at time ?

Pour ceux qui parlent français, y-a-t-il une solution pour les sous-titres sans accents bizarres ?

**Comment by mistertest** [comment]
Perhaps the solution will be to re-encode on fly the subtitle with a plugin if is exist one like that.
Or perhaps replace that's characters like str replace on php.
Si il y a des français pour travailler dessus je suis chaud !
++

**Comment by ddlstream** [comment]
salut,
nous sommes en train de développer la même choses avec les films français.

**Comment by mistertest** [comment]
Cool ddlstream je pourrais y participer normalement , et je mettrais à disposition mon thème  custom et d'autres features. On garde le contact.

**Comment by mistertest** [comment]
Quel sera le tracker fr à intégrer ? j'ai une préférence pour cpasbien , peut être que vous pensez à t411 ?

**Comment by farwarx** [comment]
T411 ou Cpasbien ont des API pour pouvoir les interroger facilement?

**Comment by ddlstream** [comment]
y me semble que T411 à une api pour ça , cpasbien je crois pas, à vérifier.

**Comment by mistertest** [comment]
Bonjour , oui pour t411 ofifcielement  https://api.t411.me/  
Pour cpasbien, rien d'officielce sont des api développé par des dev fr pour des projets similaires mais en Node webkit comme le projet streamstudio pour Ubuntu. Il ya a des scripts d'index de recherche de torrents déposés sur le github qui prenent en compte ces trackers et d'autres à intégrer manuellement mais plus simplement. Bref i faudra des bases éxistantes.

**Comment by proced** [comment]
Hum c'est compliqué a faire en fait.... car les films sur t411 ne sont en général pas au format mp4, il faut donc utilisé des plugins du type (VLC ou autres) pour la lecture .... (et donc oublié la lecture native sur les mobiles etc ...)

En plus l'api de t411 est quand meme bien pourri pour faire ce genre de chose... 

Pour les sous-titre, il me semble que j'avais vu que c'etait un probleme d'encodage, et que ce probleme était connu, mais je n'ai rien trouvé qui réencode correctement à la volé ....

J'avais regarder pour le faire aussi ... mais si il y'a besoin d'aide je peu...

**Comment by ddlstream** [comment]
Peut être on peut adapter ce-ci :
https://gist.github.com/Syskaw/5e298192cff84ee1a361

**Comment by mistertest** [comment]
Salut, Oui éxactement proced, on ne pas lire avec un lecteur web natif tout les formats et yify-pop utilise exclusivement le format mp4 pour la lecture. Des trackers comparables à yify et en fr qui auraient convertis des films en mp4 en haute qualité exclusivement, il y en a aucun à ma connaissance.L 'idéal serait de proposer la lecture sur un lecteur externe multiplateforme donc oui ddlstream Vlc serait l'idéal.Vlc quasiment tout le monde l'a sur son ordi que ça soit sur Linux, Mac ou windows.

**Comment by nilparra** [comment]
Salut

J'ai corrigé le problème des sous-titres contenant les ??

Dans le fichier /yify-pop/node_modules/opensrt_js/opensrt.js j'ai modifié le format iso par UTF8

Ligne 63 : tmp.lang = sub.UTF-8;

**Comment by mistertest** [comment]
Bonjour nilparra,  
Ha bon c'était juste ça , je pensais qu'il fallait au moins les convertir.
j'avais un peu cherché mais du côté des dossiers en rapport avec video.js, je pensais que ça venait de là. Super je testerais ça prochainement, MERCI ET  BIENVENUE.

**Comment by mistertest** [comment]
Bonjour,
Vue qu'il n'éxiste pas encore de trackers en mp4, j'oublie cette idée mais je déploie une nouvelle idée: 1 -se servir de yify-pop comme un catalogue avec lien direct sur les torrents de trackers fr 
Pouvoir parser les résultats de recherches directement dans une page node avec json et du "scraping" j'ai vue que c'était possible meme sans api officielle.
2 - Coupler yify-pop avec peerflix-server , en gros les magnets sont envoyé à peerflix server et la lecture se fait en lecture externe. Sur pc il suffit de glisser déposer le lien de streaming directe dans les lecteur videos ou en utilisant des extensions au clic droit qui permettent la lecture sur un lecteur externe. Du coup la version US ça sera vraiment quand il n'y aura pas encore de rip fr ou poour les séries .

**Comment by G-Ray** [comment]
j'ai réalisé un scraper de cpasbien pour mon projet similaire à yify-pop: https://github.com/G-Ray/candyflix.
Ca ne prend en compte que les fichiers x264 pour pouvoir lire les vidéos dans le navigateur. Je pourrais pusher sur mon repo le scraper si ça peut aider ;)

**Comment by mistertest** [comment]
Super G-ray , Oui biensur , tu utilise quoi pour scraper ? Un module node JS spécifique ?

**Comment by G-Ray** [comment]
ça donne quelque chose de ce type là https://gist.github.com/b31d5f5950dac5e96613.git

**Comment by mistertest** [comment]
Thx  G-ray je vais matter ça en détail. Comme je te l'ai dit Candyflix a l'air vraiement trop top, déjà au niveau design et ergonomie c'est encore plus pratique que Popcorn time surtout sur grand écran. Maintenant techniquement (Lecture video, fluidité) j'ai pas encore testé. j'avais un probleme pour créer un proxy pour l'installe mais j'ai trouvé une soluce. Donc je vais tester ça les jours qui suivent c'est tellement beau, bravo. Pour l'instant j'utilise yify-pop que j'ai en quelque sorte couplé à peerflix-server et chaque film renvoit sur ses liens torrents sur plusieurs trackers fr avec magnets, ensuite il faut copier le magnet et le coller dans peerflix. J'aimerais me passer d'aller sur des trackers externes et afficher en scrappant directement les résultats dans l'app directement, ça serait plus propre et y placer des boutons de copier coller. Ca marche impec, c'est très rapide et agréable mais pas encore simplifié au point de candyflix.

**Comment by G-Ray** [comment]
Merci, l'interface provient du fork time4popcorn, j'ai surtout fait une partie serveur et ajuster un peu le frontend. N'hésite pas à en parler ou y contribuer :+1:

**Comment by ddlstream** [comment]
Est pas mal tout ça G-Ray ! je vais l'installer de soir voir un peu ce que ça donne y rajouter quelques trucs à voir ;) Beau boulot.

**Comment by nilparra** [comment]
j'ai remplacé ce bon vieux Yify-pop par candy-flix :)

**Comment by mistertest** [comment]
MDr on est vite vieux sur Github, Yify-pop date du 18 Mar 2014 quasiment un An.
Tant que tout le monde trouve son bonnheur vive le Fork.

**Comment by nilparra** [comment]
Exactement question de gout et de couleur. Faut dire que G-Ray a fait du très bon boulot.

**Comment by yify-pop** [comment]
Sorry I haven't had any time for the upkeep of this project. If anyone wants to be added as a contributor and take over this repo, please contact me. Thanks.

**Comment by nilparra** [comment]
Le projet Yify-pop est donc clairement arrêté. Je vous conseille de vous tourner vers candy-flix, un fork français qui marche super bien. -> https://github.com/G-Ray/candyflix

**Comment by mistertest** [comment]
C'est sûr quand l'élève dépasse le maitre , il en a fait du next gen à lui tout seul, bravo et respect !

**Comment by mistertest** [comment]
Non nilpara il n'a pas le temps de répondre à toutes les issues et vue que celle là est encore ouverte. C'est different il recherche jsute d'autres contributeurs mais le projet n'est pas mort du tout. J'apporterais des contributions aux deux projets voire trois et n'oublie pas que ce qui fait avancer yify-pop fera forcément avancer candyflix vue que s'en est la base et qu'ils utilisent les mêmes technos et fichiers.

**Comment by mistertest** [comment]
Le jour où il décidera d'arrêter il le dira surement sur son repo et en conseillant de passer à candyflix par éxemple. Dailleurs je vais le fermer puisque tu avais trouver une solution. A bientôt .

**Comment by Hostile** [comment]
is there any similar apps like yify-pop on github?
