### ISSUE TITLE
Can't install it on Windows 7 ERROR!

### ISSUE THREAD

**Issue by ArdiArtani** [yify-pop/yify-pop#108]
i went step by step i installed geedy then peerflix when i enter npm install it runs then it shows some errors???
Download full log here http://www15.zippyshare.com/v/Vhu6yKaZ/file.html

In the end log text

4713 error Windows_NT 6.1.7601
4714 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
4715 error node v0.12.2
4716 error npm  v2.7.4
4717 error code ELIFECYCLE
4718 error bcrypt@0.7.8 install: `node-gyp rebuild`
4718 error Exit status 1
4719 error Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
4719 error This is most likely a problem with the bcrypt package,
4719 error not with npm itself.
4719 error Tell the author that this fails on your system:
4719 error     node-gyp rebuild
4719 error You can get their info via:
4719 error     npm owner ls bcrypt
4719 error There is likely additional logging output above.
4720 verbose exit [ 1, true ]
4721 verbose unbuild node_modules\bcrypt
4722 info preuninstall bcrypt@0.7.8
4723 info uninstall bcrypt@0.7.8
4724 verbose unbuild rmStuff bcrypt@0.7.8 from C:\Users\dell\Desktop\yify-pop\node_modules
4725 info postuninstall bcrypt@0.7.8
4726 silly gentlyRm C:\Users\dell\Desktop\yify-pop\node_modules\bcrypt is being purged from base C:\Users\dell\Desktop\yify-pop
4727 verbose gentlyRm don't care about contents; nuking C:\Users\dell\Desktop\yify-pop\node_modules\bcrypt
4728 silly vacuum-fs purging C:\Users\dell\Desktop\yify-pop\node_modules\bcrypt
4729 silly vacuum-fs quitting because other entries in C:\Users\dell\Desktop\yify-pop\node_modules

Thank You :)

**Comment by ArdiArtani** [comment]
i managed to fix it but now when i want to play a movie it show this ERROR

Error: 500 Internal Server Error
Error at createConstructor (C:\Users\dell\AppData\Roaming\npm\node_modules\geddy\lib\response\errors.js:68:34) at new <anonymous> (C:\Users\dell\AppData\Roaming\npm\node_modules\geddy\lib\response\errors.js:79:33) at Object.<anonymous> (C:\Users\dell\AppData\Roaming\npm\node_modules\geddy\lib\response\errors.js:21:10) at Module._compile (module.js:460:26) at Object.Module._extensions..js (module.js:478:10) at Module.load (module.js:355:32) at Function.Module._load (module.js:310:12) at Module.require (module.js:365:17) at require (module.js:384:17) at Object.<anonymous> (C:\Users\dell\AppData\Roaming\npm\node_modules\geddy\lib\controller\responder\index.js:6:14)

**Comment by Neleawan** [comment]
You are using version 0.12.2 of node (4715 error node v0.12.2). Yify-pop requires node 0.10.16.

**Comment by ejb1123** [comment]
It's this issue resolved?
