### ISSUE TITLE
Error 500 in pagination category

### ISSUE THREAD

**Issue by mistertest** [yify-pop/yify-pop#113]
Cannot read property '0' of undefined at [object Object].handleErr (/usr/lib/node_modules/geddy/lib/template/engines/ejs.js:58:15) at Object.rethrow (/usr/lib/node_modules/geddy/lib/template/engines/ejs.js:92:41) at eval (<anonymous>:2:5865) at /usr/lib/node_modules/geddy/lib/template/engines/ejs.js:103:17 at [object Object].ejs.render (/usr/lib/node_modules/geddy/lib/template/adapters/ejs.js:28:10) at [object Object].Adapter.render (/usr/lib/node_modules/geddy/lib/template/adapters/index.js:159:24) at [object Object].Partial.renderSelf (/usr/lib/node_modules/geddy/lib/template/partial.js:130:36) at handleData (/usr/lib/node_modules/geddy/lib/template/partial.js:99:16) at /usr/lib/node_modules/geddy/lib/template/partial.js:117:9 at fs.js:272:14 at Object.oncomplete (fs.js:108:15)

**Comment by Neleawan** [comment]
Do you have this problem only for the tv shows?
Because if yes, I had the same problem in the UK. Some ISP blocked the eztv API.
I use now the API through a proxy.

**Comment by mistertest** [comment]
Hello,
No it's on the movies listing when i press next for the next list, but only for 2 pages others pages are OK.
For TV show i never see that for this time.

**Comment by Hostile** [comment]
delete _session_store.json in :/var/www/yify-pop

**Comment by mistertest** [comment]
Hello it was not the problem, thx.

**Comment by ejb1123** [comment]
@mistertest does the issue still exist?

**Comment by mistertest** [comment]
Hello i think it was a problem from my vps server. I close it thx.
