### ISSUE TITLE
[Solve] Iptables

### ISSUE THREAD

**Issue by P0uet** [yify-pop/yify-pop#115]
Hi,

I just install on my own server and I would configure my iptables rules...
I would know wich ports I have to open because my strean never start and I don't find wich random ports peerfliix use...
Can I fix it in a configuration file? or wich port band can I open?

Thanks in advance!

**Comment by Hostile** [comment]
sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 4000

http://stackoverflow.com/questions/16573668/best-practices-when-running-node-js-with-port-80-ubuntu-linode

**Comment by ejb1123** [comment]
By default the ports that peerflix uses are `8889-8999` the config is located in the [stream.js file line 12](https://github.com/yify-pop/yify-pop/blob/master/app/helpers/streams.js#L12)

**Comment by P0uet** [comment]
Hi
Thanks for the ansewrs :)
If I good understood, the ports 8889-8999 are used to stream the movies, to watch it with vlc for example?
I would know if I can choose the ports wich peerflix use for the trackers and to download the torrents?
(For example, for Transmission it is by default the port 51413)

Thanks

**Comment by P0uet** [comment]
I make some research and I find something!
I modify the line 12 in stream.js file like that: --peer-port=60520 --port=' + port

It seems work, I can watch the film in vlc but anymore on the site...

![yifypop](https://cloud.githubusercontent.com/assets/12820458/8577813/773b8dc6-25ab-11e5-9b85-268f9aa59b29.png)


If you have any idea...
Tahnks
