### ISSUE TITLE
Android app + desktop app

### ISSUE THREAD

**Issue by Hostile** [yify-pop/yify-pop#116]
Hi, is this supports phone apps and desktop pc app? if yes where to get it ?

**Comment by mistertest** [comment]
you con convert your page  to apk . So it will instal a icon on dekstop.
Or seconds solutions for dekstop and mobiles/tablet to you can convert to web app launcher with firefox and chrome, so it will generated a web app launcher in your dekstop. It's a good solution beacause you'll have all features of your browser to.

Look this link : 

http://blog.laptopmag.com/how-to-create-desktop-shortcuts-for-web-pages-using-chrome

**Comment by Hostile** [comment]
thanks @mistertest , do you know any other then yify, mods of popcorn time?

Or can I do my own cloce using popcorn sources from https://git.popcorntime.io/groups/popcorntime ?

I was able to install and run yify-pop on www.vodeoo.com, but its not ideal as it downloads torrents and making disc space dissapear fast :) and thee is limits on server.

How about popcorntime app? When you clon it, are you able to control it?
Is it popcorn time app run on server same as yify pop, and desktop client connects to your server? or it not uses server.

thx

**Comment by mistertest** [comment]
Ok You should be interested in candyflix this is the solution that is more like what you want . It's a mix between poptime and yifypop , the visual interface is the same, the same code.
So you must to work on this, perhaps collaborate with the team.

All  moderns solutions about streaming torrent use node and peerflix , this is the heart of them. 
And yify pop and candyflix use power of the server for peerflix opperations. if you don't want use a server you must have to use dekstop version or your local server it 's possible for peerflix.

https://github.com/G-Ray/candyflix

**Comment by mistertest** [comment]
For completing the reponse to the question original and help people : 
To make a web laucher for your mobile or box tv android ...

http://stackoverflow.com/questions/22167594/create-a-android-launch-icon-for-website

For convert a web site  to  a apk : 
http://www.appsgeyser.com/
