### ISSUE TITLE
Change tmp folder 

### ISSUE THREAD

**Issue by ArdiArtani** [yify-pop/yify-pop#118]
how can i change the tmp folder from C:\ to somewhere else for example D:\ drive ??

**Comment by ArdiArtani** [comment]
anyone ?????

**Comment by ejb1123** [comment]
replace `osSpecificArgs` varible in the stream.js file with `var osSpecificArgs = isWin ? ['/c', 'peerflix', decodeURIComponent(params.file), '--port=' + port,'--path=D:\\'] : [decodeURIComponent(params.file), '--port=' + port];`
The reason that there is two `\\` at the end is that `\` is a escape character in javascript.

**Comment by ArdiArtani** [comment]
Thank you it worked !!! :)
