### ISSUE TITLE
Trying to add some features

### ISSUE THREAD

**Issue by ArdiArtani** [yify-pop/yify-pop#119]
Can someone help me??

I did my own custom design i added some features i will take a screenshot and post it later :)

I want to add some features.

1. Upload or enter torrent link 
2. Movies details in streaming page (plot,title, poster, runtime, background image etc)

And i can't create a user account when i go to users/add I keep getting a error.

**Comment by Porco-Rosso** [comment]
It's been awhile but if I recall correctly, you need to generate a secret before you can add users.
Check this out it might fix your issue: https://github.com/yify-pop/yify-pop/issues/88

Hope you succeed on the torrent link one, it's an obvious feature that has been missing.

**Comment by ArdiArtani** [comment]
@Porco-Rosso Thank You but i already managed to fix it :)

**Comment by ArdiArtani** [comment]
@ejb1123 Can you tell me how to show plot, title and other details in streaming page ??

**Comment by ejb1123** [comment]
in the `movies.js` stream function add `yifyresponse = geddy.config.streamingProcesses[i].data;` to the if statement
and add `yifyresponse: yifyresponse` to self.respond({param1},{parm2}) param1
```
this.stream = function (req, resp, params) {
    var self = this;
    var streamURL = false;

    var hostname = (req.headers.host.match(/:/g)) ? req.headers.host.slice(0, req.headers.host.indexOf(":")) : req.headers.host;

    // Check if there is already a stream running for this torrent
    for (var i=0; i < geddy.config.streamingProcesses.length; i++) {
      if (decodeURIComponent(params.file) === geddy.config.streamingProcesses[i].torrent) {
        streamURL = geddy.config.streamingProcesses[i].stream;
        subtitles = geddy.config.streamingProcesses[i].subtitles;
        yifyresponse = geddy.config.streamingProcesses[i].yifyresponse;
      }
    }

    if (streamURL) {
      self.respond({
        params: params,
        streamURL: streamURL,
        subtitles: subtitles,
        yifyresponse: yifyresponse
      }, {
        format: 'html',
        template: 'app/views/main/stream'
      });
    } else {
      // Otherwise start a new stream
      streams.create(self, streamURL, hostname, params);
    }
  };
```
add `yifyresponse:yifyResponse` to geddy.config.streamingProcesses.push and self.respond in streams.js
```
childStream.start(function(pid){
                  geddy.config.streamingProcesses.push({
                    pid: pid,
                    child: childStream,
                    torrent: decodeURIComponent(params.file),
                    stream: streamURL,
                    data: data,
                    subtitles: subtitles,
                    yifyresponse:yifyResponse
                  });
                });

                self.respond({
                  params: params,
                  streamURL: streamURL,
                  subtitles: subtitles,
                  yifyresponse:yifyResponse
                }, {
                  format: 'html',
                  template: 'app/views/main/stream'
                });
```
use <%= yifyresponse.data.description_full%> in the stream.html.ejs file to get the data

``` json
{

    "status":"ok",
    "status_message":"Query was successful",
    "data":{
        "id":10,
        "url":"https://yts.to/movie/snatch-2000",
        "imdb_code":"tt0208092",
        "title":"Snatch.",
        "title_long":"Snatch. (2000)",
        "slug":"snatch-2000",
        "year":2000,
        "rating":8.3,
        "runtime":102,
        "genres":[
            "Comedy",
            "Crime"
        ],
        "language":"English",
        "mpa_rating":"R",
        "download_count":269271,
        "like_count":293,
        "rt_critics_score":73,
        "rt_critics_rating":"Fresh",
        "rt_audience_score":93,
        "rt_audience_rating":"Upright",
        "description_intro":"Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers, and supposedly Jewish jewelers fight to track down a priceless stolen diamond.",
        "description_full":"Turkish and his close friend/accomplice Tommy get pulled into the world of match fixing by the notorious Brick Top. Things get complicated when the boxer they had lined up gets badly beaten by Pitt, a 'pikey' ( slang for an Irish Gypsy)- who comes into the equation after Turkish, an unlicensed boxing promoter wants to buy a caravan off the Irish Gypsies. They then try to convince Pitt not only to fight for them, but to lose for them too. Whilst all this is going on, a huge diamond heist takes place, and a fistful of motley characters enter the story, including 'Cousin Avi', 'Boris The Blade', 'Franky Four Fingers' and 'Bullet Tooth Tony'. Things go from bad to worse as it all becomes about the money, the guns, and the damned dog!",
        "yt_trailer_code":"PvQnBwDejfw",
        "date_uploaded":"2011-08-02 22:12:51",
        "date_uploaded_unix":1312279971,
        "torrents":[
            {
                "url":"https://yts.to/torrent/download/513EC39C73135C43AACACECDC78B300161902A45.torrent",
                "hash":"513EC39C73135C43AACACECDC78B300161902A45",
                "quality":"720p",
                "resolution":"1280*688",
                "framerate":23.976,
                "seeds":351,
                "peers":43,
                "size":"449.71 MB",
                "size_bytes":471555113,
                "download_count":269271,
                "date_uploaded":"2011-08-02 22:12:51",
                "date_uploaded_unix":1312279971
            }
        ]
    },
    "@meta":{
        "server_time":1436019943,
        "server_timezone":"Pacific/Auckland",
        "api_version":2,
        "execution_time":"10.9 ms"
    }

}
```

**Comment by ArdiArtani** [comment]
Thank you it worked!! but you wrote yifyresponse = geddy.config.streamingProcesses[i].yifyresponse; instead of         yifyresponse = geddy.config.streamingProcesses[i].data; in the full code like the one down.


this.stream = function (req, resp, params) {
    var self = this;
    var streamURL = false;

    var hostname = (req.headers.host.match(/:/g)) ? req.headers.host.slice(0, req.headers.host.indexOf(":")) : req.headers.host;

    // Check if there is already a stream running for this torrent
    for (var i=0; i < geddy.config.streamingProcesses.length; i++) {
      if (decodeURIComponent(params.file) === geddy.config.streamingProcesses[i].torrent) {
        streamURL = geddy.config.streamingProcesses[i].stream;
        subtitles = geddy.config.streamingProcesses[i].subtitles;
        yifyresponse = geddy.config.streamingProcesses[i].data;
      }
    }

    if (streamURL) {
      self.respond({
        params: params,
        streamURL: streamURL,
        subtitles: subtitles,
        yifyresponse: yifyresponse
      }, {
        format: 'html',
        template: 'app/views/main/stream'
      });
    } else {
      // Otherwise start a new stream
      streams.create(self, streamURL, hostname, params);
    }
  };

**Comment by ArdiArtani** [comment]
there is one problem when i click a movie that it wasn't played it works but when i click in the same movie or when i go to now playing and click the movie it doesnt work it shows a error


TypeError: ejs:136 134| </script> 135| >> 136| <%= yifyresponse.data.description_full%> Cannot read property 'description_full' of undefined at handleErr (C:\Users\hp\AppData\Roaming\npm\node_modules\geddy\lib\template\engines\ejs.js:58:15) at Object.rethrow (C:\Users\hp\AppData\Roaming\npm\node_modules\geddy\lib\template\engines\ejs.js:92:41) at eval (eval at <anonymous> (C:\Users\hp\AppData\Roaming\npm\node_modules\geddy\lib\template\engines\ejs.js:90:10), <anonymous>:2:3890) at C:\Users\hp\AppData\Roaming\npm\node_modules\geddy\lib\template\engines\ejs.js:103:17 at ejs.render (C:\Users\hp\AppData\Roaming\npm\node_modules\geddy\lib\template\adapters\ejs.js:28:10) at Adapter.render (C:\Users\hp\AppData\Roaming\npm\node_modules\geddy\lib\template\adapters\index.js:159:24) at Partial.renderSelf (C:\Users\hp\AppData\Roaming\npm\node_modules\geddy\lib\template\partial.js:130:36) at handleData (C:\Users\hp\AppData\Roaming\npm\node_modules\geddy\lib\template\partial.js:99:16) at C:\Users\hp\AppData\Roaming\npm\node_modules\geddy\lib\template\partial.js:117:9 at fs.js:266:14

**Comment by ejb1123** [comment]
If you use `yifyresponse = geddy.config.streamingProcesses[i].yifyresponse;` it won't throw the error.
