### ISSUE TITLE
Yify-pop using my reversed url

### ISSUE THREAD

**Issue by psycholyzern** [yify-pop/yify-pop#131]
I setup reverse proxy using apache2.

```
ProxyPass / http://127.0.0.1:4000/
ProxyPassReverse / http://127.0.0.1:4000/
```

But all movie list at homepage have this url => ```http://127.0.0.1:4000/stream?id=4579&file=https%3A%2F%2Fyts.to%2Ftorrent%2Fdownload%2F88323B2DC709A2B3049BDACC38C9B66C0AD9B1AF.torrent```

How to fix?

**Comment by psycholyzern** [comment]
Problem solved. I made a quick search and found that ```baseURL``` is holding the value of host.
So, I edited these two lines:
- ```https://github.com/yify-pop/yify-pop/blob/ea38a0267b83e726e042f619099fc5e93685c035/app/controllers/shows.js#L32```
- ```https://github.com/yify-pop/yify-pop/blob/ea38a0267b83e726e042f619099fc5e93685c035/app/controllers/movies.js#L33```

I changed ```"http://" + req.headers.host``` to my domain.
Now all working great!!!

**Comment by Porco-Rosso** [comment]
on nginx, I am using the config below for a simple subdomain reverse proxy, might help someone.
```
server {
    listen      80;
    server_name yify.domain.com;
    rewrite     ^   https://$server_name$request_uri? permanent;
}

server {
    listen  443 ssl;
    server_name yify.domain.com;

    ssl on;
    ssl_certificate     /etc/nginx/ssl/nginx.crt; # The certificate file
    ssl_certificate_key /etc/nginx/ssl/nginx.key; # The private key file
    ssl_session_timeout  5m;

    location / {
        proxy_pass_header Server;

        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_connect_timeout 10;
        proxy_read_timeout 10;
        proxy_pass http://INTERNALIP:4000/;
    }
}
```

**Comment by psycholyzern** [comment]
oh.. thanks :)
