### ISSUE TITLE
endles loading

### ISSUE THREAD

**Issue by DeeJaVu** [yify-pop/yify-pop#133]
hello, port 4000 is open but when i browse to http://myip:4000/ it is just loading without rendering

**Comment by phenixtai** [comment]
hello, same for me on DS3615xs it seem ....
ne error, i install :
geddy
peerflix
node-gyc with make + python 2.7 + gcc 
and when i launch geddy : everything seem ok : 
![1](https://cloud.githubusercontent.com/assets/16016811/11397585/e91f40c6-937a-11e5-8010-59a869591539.jpg)
![2](https://cloud.githubusercontent.com/assets/16016811/11397595/fd9a9ffa-937a-11e5-80ec-10f898c21ad1.jpg)

but when i browse to http://myip:4000/ it is just loading without rendering

**Comment by phenixtai** [comment]
we must do the command : npm install in the folder app or in the root of the folder yify-pop-master ?
but i don't think is my problem because geddy launch yify-pop ???? port are open on the router and iptables .... 
synology ..... not really a server i know, i know lol :-)
