### ISSUE TITLE
Automatically clean download cache

### ISSUE THREAD

**Issue by tcitworld** [yify-pop/yify-pop#53]
Hi,
After a video is seen, or ever if the screening has been stopped before the end, the file stays written on hard drive. Is there a way to automatically delete these files after some time, or limit the size of the folder containing them ?

**Comment by ligol** [comment]
A quick and dirty fix to use the -r option is to change the line 17 in the file stream.js in app/helper/ and add the -r options to the argument passed to peerflix.

Like this line:
var osSpecificArgs = isWin ? ['/c', 'peerflix', decodeURIComponent(params.file),  '--port=' + port, '-r'] : [decodeURIComponent(params.file),  '--port=' + port, '-r'];

After this you just need to click on delete in the section "Now Playing" to remove the stream from the folder.

**Comment by iMilnb** [comment]
Naïve request: couldn't this be the default behavior? or at least configurable? It took me a while before I realized the files were stored there and thus eating all of my root partition space :/
Thanks a lot @ligol for this precious information.

**Comment by mistertest** [comment]
Hello. For you.
If you like erase tmp destination on linux Ubuntu you can use tmpreaper.
But be carefull about the command it's dangerous .
So if you want to erase every 8 hours your must to do 

tmpreaper -a 8h /tmp/your_download_folder

http://www.thegeekstuff.com/2013/10/tmpreaper-examples/
