### ISSUE TITLE
Cannot read property 'accessTime' of undefined

### ISSUE THREAD

**Issue by parquetn** [yify-pop/yify-pop#76]
Hello all,

Installed yify-pop a few days ago on my Raspberry pi. Worked great until now but I got this error message preventing me from using it:
TypeError: Cannot read property 'accessTime' of undefined
    at get (/usr/local/lib/node_modules/geddy/lib/sessions/index.js:130:21)
    at isExpired (/usr/local/lib/node_modules/geddy/lib/sessions/index.js:108:36)
    at localCallback (/usr/local/lib/node_modules/geddy/lib/sessions/index.js:95:16)
    at /usr/local/lib/node_modules/geddy/lib/sessions/stores/filesystem.js:58:7
    at /usr/local/lib/node_modules/geddy/lib/sessions/stores/filesystem.js:90:7
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)

I could not find any thread about this until now and could not find how to solve this. Anyone would have a hint ?
Thank you!

**Comment by inkubux** [comment]
I have the same issue on my server

**Comment by phanect** [comment]
Hi,
I experienced the same error in my own geddy based app, and google find this issue.

`accessTime` property is stored in _session_store.json, so remove it and you can solve the problem.

Geddy, which yify-pop use as framework, seems to have bug to generate invalid _session_store.json occasionally.

**Comment by iMilnb** [comment]
Thanks @phanect, got that exact same issue, did what you wrote, fixed the issue :)

**Comment by parquetn** [comment]
Yes ! That also resolves the issue for me. Thank you
