### ISSUE TITLE
Force auth with passport

### ISSUE THREAD

**Issue by farwarx** [yify-pop/yify-pop#87]
Hi,
Anyone knows how to force the login auth in this app?
I test with this doc: http://geddyjs.org/guide#authentication (in this file: app/controllers/main.js).
But no sucess :/

Login works with redirect. I don't want an apache auth because i want save a database.json by user (favorite/seen).

If anyone can help me, thanks.
NB: sorry, i'm not a dev, i'm just a sysadmin.

**Comment by dfmcphee** [comment]
This is definitely possible, but will take some re-factoring. I think a lot of the functions will need to be pulled out of the main controller and moved into something like a streams controller. This would allow for other customization based on user accounts as well. I think it is definitely the way to go.

**Comment by dfmcphee** [comment]
I just pushed a commit that will allow this. If you change private to true in config/development.js it will force you to be logged in to view any of the pages. To create a user account just go to /users/add.

**Comment by farwarx** [comment]
So good, thanks a lot.
It works like a charm!!!!!!!
