### ISSUE TITLE
after passport added there is some error

### ISSUE THREAD

**Issue by korrio** [yify-pop/yify-pop#88]
Error: 500 Internal Server Error
Error: Need application secret at exports.generateHash (/root/yify-auth/app/helpers/passport/index.js:23:11) at /root/yify-auth/app/controllers/users.js:44:27 at utils.mixin.load (/usr/local/lib/node_modules/geddy/node_modules/model/lib/adapters/memory/index.js:132:7) at Object.obj.all (/usr/local/lib/node_modules/geddy/node_modules/model/lib/index.js:394:25) at Function.obj.first (/usr/local/lib/node_modules/geddy/node_modules/model/lib/index.js:356:18) at create (/root/yify-auth/app/controllers/users.js:31:22) at callback [as last] (/usr/local/lib/node_modules/geddy/lib/controller/base_controller.js:356:24) at async.AsyncBase.next (/usr/local/lib/node_modules/geddy/node_modules/utilities/lib/async.js:123:12) at utils.mixin._execFilters (/usr/local/lib/node_modules/geddy/lib/controller/base_controller.js:239:11) at utils.mixin._handleAction (/usr/local/lib/node_modules/geddy/lib/controller/base_controller.js:367:20)

This happens when I add new user from /users/add

**Comment by dfmcphee** [comment]
Try running `geddy gen secret` and see if it fixes it.

**Comment by korrio** [comment]
root@***:~/yify-auth# geddy gen secret
There is no file /root/yify-auth/config/secrets.json to add data to.
Added app-secret to config/secrets.json.
DO NOT add this file into your revision control.
DO make a backup of it, keep it someplace safe.

**Comment by farwarx** [comment]
Don't forget the secret in config/development.js

, private: true
, secret: "MY SECRET KEY"
};

**Comment by dfmcphee** [comment]
That command should have generated a secret for you in config/secrets.json. You should be able to just run the app again and create a user.

**Comment by my90558** [comment]
I am also experiencing the same problem when trying to add a user.

**Comment by my90558** [comment]
Manually changing the secret as suggested by farwarx fixed the problem

**Comment by my90558** [comment]
Also, why was the email verification option removed?

**Comment by dfmcphee** [comment]
I removed the email verification because I also removed the email and name properties from the user model. I figured tracking information like that was probably not a good idea.
