### ISSUE TITLE
No Subtitle

### ISSUE THREAD

**Issue by Bodhiz** [yify-pop/yify-pop#92]
Hi,

I can't see any subtitle button on the player and nothing is downloaded in the public/subtitles folder.
Are you aware of this issue ? 

Thanks

**Comment by korrio** [comment]
Me too. No subtitle.
It's because yifysubtitles.com's API is changed ?

**Comment by Bodhiz** [comment]
It was I thought too.

**Comment by walidsa3d** [comment]
I second that, no subtitle button.

**Comment by andreabat** [comment]
Same for me

**Comment by Jumanjii** [comment]
Idem, i begin to see why

**Comment by KilianMahe** [comment]
Same for me !
Any news ?

**Comment by korrio** [comment]
News is YIFY-subtitle API is changed, need to adjust. I think I will send pull request.
