### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by NickSarath** [yify-pop/yify-pop#98]
I got the following error during the installation of yify-pop when I did the command "npm install"

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Downloads/yify-pop/node_modules/bcrypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm WARN engine xmlbuilder@2.4.6: wanted: {"node":"0.8.x || 0.10.x || 0.11.x  || 1.0.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Downloads/yify-pop/npm-debug.log

I've tried doing "sudo npm install yify-pop and the following is what I got in return

npm WARN package.json yify-pop@0.0.1 No repository field.
npm WARN install Refusing to install yify-pop as a dependency of itself

How do I fix this? Looking forward to a solution, thank you in advance.

**Comment by yify-pop** [comment]
Try installing a 0.10.x version of node and running again.

**Comment by NickSarath** [comment]
Thank you, It works now. So am I basically archiving copyrighted materials if I deploy yify-pop onto the web? I mean the torrent contents are streamed to the client and my servers would basically be downloading all the movies correct? So this is basically something I cant deploy and share with other people? I've got to keep it hosted locally?

**Comment by ejb1123** [comment]
can you see if your issue is resolved?
